[package]
name = "cosmic-settings-daemon-subscription"
version = "1.0.7"
edition = "2024"
rust-version.workspace = true
publish = true

[dependencies]
futures = "0.3.32"
iced_futures = { git = "https://github.com/Matrinsoft/liblingmo" }
log = "0.4.33"
tokio = "1.49"
tokio-stream = "0.1.14"
zbus = "5.14"
